In [5]:
from sklearn.datasets import load_iris

In [6]:
iris = load_iris()

In [12]:
print(type(iris))          # <class 'sklearn.utils.Bunch'>

<class 'sklearn.utils.Bunch'>


In [13]:
print(iris.data.shape)    # print shape of data

(150, 4)


In [7]:
print(iris['feature_names'])    # ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [36]:
n_samples, n_features = iris.data.shape

print(n_samples, n_features)

150 4


In [14]:
print(iris.keys())  # dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [15]:
print(iris.target_names)       # ['setosa' 'versicolor' 'virginica']

['setosa' 'versicolor' 'virginica']


In [17]:
print(iris['target_names'])     # ['setosa' 'versicolor' 'virginica']

['setosa' 'versicolor' 'virginica']


In [18]:
print(iris["target_names"])     # ['setosa' 'versicolor' 'virginica']

['setosa' 'versicolor' 'virginica']


In [19]:
print(iris.target.shape)      # (150,)

(150,)


In [26]:
import numpy as np

np.bincount(iris.target)           # array([50, 50, 50], dtype=int64)

array([50, 50, 50], dtype=int64)

In [27]:
print(iris.target)       # 0-50,  1-50, 2-50

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [28]:
print(iris.data[0])   # [5.1 3.5 1.4 0.2]      - frist row of data

[5.1 3.5 1.4 0.2]


In [31]:
print(iris.data[149])     # [5.9 3.  5.1 1.8]      - last row of data

[5.9 3.  5.1 1.8]


In [41]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
print(iris.data[iris.target[2]])

In [45]:
print(iris.data[50])

[7.  3.2 4.7 1.4]


In [46]:
print(iris.data[50, 3])

1.4


In [47]:
print(iris.data[[50, 100, 149]])

[[7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]
 [5.9 3.  5.1 1.8]]


In [48]:
print(iris.data[[50, 100, 149], 1])

[3.2 3.3 3. ]


In [49]:
print(iris.data[[50, 100, 149], :])

[[7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]
 [5.9 3.  5.1 1.8]]


In [50]:
print(iris.data[[50, 100, 149], 1:])

[[3.2 4.7 1.4]
 [3.3 6.  2.5]
 [3.  5.1 1.8]]
