In [2]:
# SPLITTINGIRIS DATA SET      - MANUAL METHOD
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()

iris.data.shape , iris.target.shape

((150, 4), (150,))

In [3]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
np.bincount(iris.target)

array([50, 50, 50], dtype=int64)

In [6]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
"""
If we were to split our data in the ratio 2/3 (learning set) and 1/3 (test set), the learning set would contain all
the flowers of the first two classes and the test set all the flowers of the third flower class. The classifier could
only learn two classes and the third class would be completely unknown. So we urgently need to mix the data
"""

In [7]:
np.random.permutation(10)

array([0, 9, 2, 6, 7, 5, 3, 1, 8, 4])

In [8]:
indices = np.random.permutation(len(iris.data))
indices

array([ 52, 136,  54,  10,  57, 110,  96,  89,  90, 145, 112, 118,  15,
       138,  20,  39,  81,  85, 126,  61, 131,  58,  36,  82,   8,  25,
        73, 148,   6,  79,  44, 101,  12,  35,  18, 133,  66, 117, 135,
        68,   4,  94,  53,  47,  63,  50, 119, 147, 146, 144,  56, 141,
        26,  86, 127,  62,  29,   9, 143,   7, 123,  95, 129,   0,  93,
        67, 128, 121,  45,  64,  11,  40,  41,  21,  75,  42, 137, 102,
        27,  98,  55,  31,  46,  23, 108,  70, 125,  59,  76, 104,  13,
        30, 100, 149,  24,  33, 134, 107,  48, 109,   5,   3, 132, 111,
       116,  28,  19,  92, 139,  16,  97, 114,  32,  72, 106,  17,  22,
        43, 115, 122,  49,  34,  88,  38,  77, 103,  91,  78,   2,  14,
       142,  65,  51, 140,  84,  99, 124,   1,  69,  80, 113,  87,  83,
       105,  37,  60,  71, 120, 130,  74])

In [9]:
n_test_samples = 50
learn_data = iris.data[indices[:-n_test_samples]]
learn_data

array([[6.9, 3.1, 4.9, 1.5],
       [6.3, 3.4, 5.6, 2.4],
       [6.5, 2.8, 4.6, 1.5],
       [5.4, 3.7, 1.5, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [6.5, 3.2, 5.1, 2. ],
       [5.7, 2.9, 4.2, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.7, 3. , 5.2, 2.3],
       [6.8, 3. , 5.5, 2.1],
       [7.7, 2.6, 6.9, 2.3],
       [5.7, 4.4, 1.5, 0.4],
       [6. , 3. , 4.8, 1.8],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6. , 3.4, 4.5, 1.6],
       [6.2, 2.8, 4.8, 1.8],
       [5.9, 3. , 4.2, 1.5],
       [7.9, 3.8, 6.4, 2. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.5, 3.5, 1.3, 0.2],
       [5.8, 2.7, 3.9, 1.2],
       [4.4, 2.9, 1.4, 0.2],
       [5. , 3. , 1.6, 0.2],
       [6.1, 2.8, 4.7, 1.2],
       [6.2, 3.4, 5.4, 2.3],
       [4.6, 3.4, 1.4, 0.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.1, 3.8, 1.9, 0.4],
       [5.8, 2.7, 5.1, 1.9],
       [4.8, 3. , 1.4, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.7, 3

In [10]:
learn_data.shape

(100, 4)

In [11]:
learn_labels = iris.target[indices[:-n_test_samples]]
learn_labels

array([1, 2, 1, 0, 1, 2, 1, 1, 1, 2, 2, 2, 0, 2, 0, 0, 1, 1, 2, 1, 2, 1,
       0, 1, 0, 0, 1, 2, 0, 1, 0, 2, 0, 0, 0, 2, 1, 2, 2, 1, 0, 1, 1, 0,
       1, 1, 2, 2, 2, 2, 1, 2, 0, 1, 2, 1, 0, 0, 2, 0, 2, 1, 2, 0, 1, 1,
       2, 2, 0, 1, 0, 0, 0, 0, 1, 0, 2, 2, 0, 1, 1, 0, 0, 0, 2, 1, 2, 1,
       1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2])

In [12]:
learn_labels.shape

(100,)

In [13]:
test_data = iris.data[indices[-n_test_samples:]]
test_data.shape

(50, 4)

In [14]:
test_data

array([[5.4, 3.9, 1.7, 0.4],
       [4.6, 3.1, 1.5, 0.2],
       [6.4, 2.8, 5.6, 2.2],
       [6.4, 2.7, 5.3, 1.9],
       [6.5, 3. , 5.5, 1.8],
       [5.2, 3.4, 1.4, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [5.8, 2.6, 4. , 1.2],
       [6.9, 3.1, 5.4, 2.1],
       [5.4, 3.9, 1.3, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5.8, 2.8, 5.1, 2.4],
       [5.2, 4.1, 1.5, 0.1],
       [6.3, 2.5, 4.9, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [5.1, 3.5, 1.4, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [5. , 3.5, 1.6, 0.6],
       [6.4, 3.2, 5.3, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [5. , 3.3, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5.6, 3. , 4.1, 1.3],
       [4.4, 3. , 1.3, 0.2],
       [6.7, 3. , 5. , 1.7],
       [6.3, 2.9, 5.6, 1.8],
       [6.1, 3. , 4.6, 1.4],
       [6. , 2.9, 4.5, 1.5],
       [4.7, 3.2, 1.3, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [6.7, 3.1, 4.4, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.7, 3.1, 5.6, 2.4],
       [5.4, 3

In [15]:
test_labels = iris.target[indices[-n_test_samples:]]
test_labels

array([0, 0, 2, 2, 2, 0, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 0, 2, 2, 0, 0,
       1, 0, 1, 2, 1, 1, 0, 0, 2, 1, 1, 2, 1, 1, 2, 0, 1, 1, 2, 1, 1, 2,
       0, 1, 1, 2, 2, 1])

In [16]:
test_labels.shape

(50,)

In [18]:
learn_data[:4] , learn_labels[:4]

(array([[6.9, 3.1, 4.9, 1.5],
        [6.3, 3.4, 5.6, 2.4],
        [6.5, 2.8, 4.6, 1.5],
        [5.4, 3.7, 1.5, 0.2]]),
 array([1, 2, 1, 0]))