In [ ]:
"""
STRATIFIED RANDOM SAMPLE
Especially with relatively small amounts of data, it is better to stratify the division. Stratification means that
we keep the original class proportion of the data set in the test and training sets. We calculate the class
proportions of the previous split in percent using the following code. To calculate the number of occurrences
of each class, we use the numpy function 'bincount'. It counts the number of occurrences of each value in the
array of non-negative integers passed as an argument.

"""

In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np

iris = load_iris()
data, labels = iris.data, iris.target

res = train_test_split(data, labels, train_size=0.8, test_size=0.2, random_state=42)

train_data, test_data, train_labels, test_labels = res

In [11]:
res[0].shape, res[1].shape, res[2].shape, res[3].shape

((120, 4), (30, 4), (120,), (30,))

In [5]:
np.bincount(labels)

array([50, 50, 50], dtype=int64)

In [6]:
np.bincount(labels)/len(labels) * 100                    # original class portions

array([33.33333333, 33.33333333, 33.33333333])

In [9]:
np.bincount(train_labels)

array([40, 41, 39], dtype=int64)

In [7]:
np.bincount(train_labels)/len(train_labels) * 100         # stratified training portions

array([33.33333333, 34.16666667, 32.5       ])

In [10]:
np.bincount(test_labels)

array([10,  9, 11], dtype=int64)

In [8]:
np.bincount(test_labels)/len(test_labels) * 100           # stratified testing portions

array([33.33333333, 30.        , 36.66666667])