In [3]:
"""
To stratify the division, we can pass the label array as an additional argument to the train_test_split function:
"""
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np

iris = load_iris()

data, labels = iris.data, iris.target

res = train_test_split(data, labels, train_size=0.8, test_size=0.2, random_state=42, stratify=labels)

train_data, test_data, train_labels, test_labels = res


In [4]:
# lets see the stratified values when stratify argument is used
np.bincount(train_labels)

array([40, 40, 40], dtype=int64)

In [6]:
np.bincount(labels)/len(labels) * 100             # original

array([33.33333333, 33.33333333, 33.33333333])

In [7]:
np.bincount(train_labels)/len(train_labels) * 100        # stratified training

array([33.33333333, 33.33333333, 33.33333333])

In [8]:
np.bincount(test_labels)/len(test_labels) * 100         # stratified testing

array([33.33333333, 33.33333333, 33.33333333])