In [3]:
from sklearn.model_selection import train_test_split
import numpy as np

content = np.loadtxt("strange_flowers.txt", delimiter=" ")
content

array([[250.  ,  94.  ,   6.  ,   3.98,   1.  ],
       [247.  , 102.  ,   3.  ,   3.51,   1.  ],
       [251.  , 114.  ,  15.  ,   3.59,   1.  ],
       ...,
       [197.  , 244.  ,  95.  ,   2.87,   4.  ],
       [197.  , 252.  , 101.  ,   2.89,   4.  ],
       [197.  , 254.  , 104.  ,   3.28,   4.  ]])

In [45]:
data = content[:, :-1]
data.shape 

(795, 4)

In [46]:
type(data)

numpy.ndarray

In [66]:
data

array([[250.  ,  94.  ,   6.  ,   3.98],
       [247.  , 102.  ,   3.  ,   3.51],
       [251.  , 114.  ,  15.  ,   3.59],
       ...,
       [197.  , 244.  ,  95.  ,   2.87],
       [197.  , 252.  , 101.  ,   2.89],
       [197.  , 254.  , 104.  ,   3.28]])

In [42]:
data.ndim

2

In [68]:
labels = content[:, -1:]               # give [[]]    - 2D array instead a 1D array
labels.ndim

2

In [69]:
labels.shape

(795, 1)

In [59]:
labels

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [70]:
type(labels)

numpy.ndarray

In [76]:
labels = content[:, -1]               # 1D  array
labels.ndim

1

In [77]:
labels

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2.

In [78]:
type(labels)

numpy.ndarray

In [79]:
labels.shape

(795,)

In [85]:
np.bincount(labels.astype(int))                          # original bincounts

array([  0, 190, 205, 230, 170], dtype=int64)

In [86]:
np.bincount(labels.astype(int))/len(labels) * 100        # original ratios

array([ 0.        , 23.89937107, 25.78616352, 28.93081761, 21.3836478 ])

In [83]:
res = train_test_split(data, labels, train_size=0.8, test_size=0.2, random_state=32, stratify=labels)

In [84]:
train_data, test_data, train_labels, test_labels = res

In [88]:
train_data.shape, test_data.shape, train_labels.shape, test_labels.shape     

((636, 4), (159, 4), (636,), (159,))

In [90]:
np.bincount(train_labels.astype(int))/len(train_labels) * 100

array([ 0.        , 23.89937107, 25.78616352, 28.93081761, 21.3836478 ])

In [92]:
np.bincount(test_labels.astype(int))/len(test_labels) * 100

array([ 0.        , 23.89937107, 25.78616352, 28.93081761, 21.3836478 ])