In [ ]:
"""
reshape and concatenate
"""

In [1]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

In [2]:
a

array([[1, 2],
       [3, 4]])

In [3]:
a.shape

(2, 2)

In [4]:
b = np.array([5, 6])
b

array([5, 6])

In [5]:
b.shape

(2,)

In [7]:
b = b.reshape(b.shape[0], 1)
b

array([[5],
       [6]])

In [8]:
b.shape

(2, 1)

In [9]:
x = np.concatenate((a, b), axis=1)
x

array([[1, 2, 5],
       [3, 4, 6]])

In [10]:
x.shape

(2, 3)